In [4]:
import pandas as pd
import json

In [3]:
train = "train.json"
test = "test.json"

In [17]:
with open(train, "r") as f:
    data=json.load(f)

In [18]:
info_df = pd.DataFrame([data["info"]])  # single dict
audio_df = pd.DataFrame(data["audio"])
categories_df = pd.DataFrame(data["categories"])
annotations_df = pd.DataFrame(data["annotations"])
licenses_df = pd.DataFrame(data["licenses"])

In [33]:
categories_df

,id,name,common_name,supercategory,kingdom,phylum,class,order,family,genus,specific_epithet,audio_dir_name,evaluation
0,0,Hodotermes mossambicus,Northern Harvester Termite,Insecta,Animalia,Arthropoda,Insecta,Blattodea,Hodotermitidae,Hodotermes,mossambicus,00000_Animalia_Arthropoda_Insecta_Blattodea_Ho...,0
1,1,Brachinus sclopeta,,Insecta,Animalia,Arthropoda,Insecta,Coleoptera,Carabidae,Brachinus,sclopeta,00001_Animalia_Arthropoda_Insecta_Coleoptera_C...,0
2,2,Acanthinodera cumingii,,Insecta,Animalia,Arthropoda,Insecta,Coleoptera,Cerambycidae,Acanthinodera,cumingii,00002_Animalia_Arthropoda_Insecta_Coleoptera_C...,0
3,3,Agapanthia violacea,,Insecta,Animalia,Arthropoda,Insecta,Coleoptera,Cerambycidae,Agapanthia,violacea,00003_Animalia_Arthropoda_Insecta_Coleoptera_C...,0
4,4,Anoplophora chinensis,Citrus Long-horned Beetle,Insecta,Animalia,Arthropoda,Insecta,Coleoptera,Cerambycidae,Anoplophora,chinensis,00004_Animalia_Arthropoda_Insecta_Coleoptera_C...,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5564,5564,Crotalus pyrrhus,Southwestern Speckled Rattlesnake,Reptilia,Animalia,Chordata,Reptilia,Squamata,Viperidae,Crotalus,pyrrhus,05564_Animalia_Chordata_Reptilia_Squamata_Vipe...,0
5565,5565,Crotalus ruber,Red Diamond Rattlesnake,Reptilia,Animalia,Chordata,Reptilia,Squamata,Viperidae,Crotalus,ruber,05565_Animalia_Chordata_Reptilia_Squamata_Vipe...,0
5566,5566,Crotalus viridis,Prairie Rattlesnake,Reptilia,Animalia,Chordata,Reptilia,Squamata,Viperidae,Crotalus,viridis,05566_Animalia_Chordata_Reptilia_Squamata_Vipe...,0
5567,5567,Sistrurus catenatus,Massasauga,Reptilia,Animalia,Chordata,Reptilia,Squamata,Viperidae,Sistrurus,catenatus,05567_Animalia_Chordata_Reptilia_Squamata_Vipe...,0
5568,5568,Vipera aspis,Asp Viper,Reptilia,Animalia,Chordata,Reptilia,Squamata,Viperidae,Vipera,aspis,05568_Animalia_Chordata_Reptilia_Squamata_Vipe...,0

In [49]:
annotations_df

            id  audio_id  category_id
0       156691    156691         3612
1       182163    182163         4361
2        19703     19703          911
3        61500     61500         2061
4       224298    224298         5147
...        ...       ...          ...
137007  139505    139505         3479
137008  102836    102836         2760
137009  135022    135022         3448
137010   73921     73921         2376
137011   31711     31711         1182

[137012 rows x 3 columns]

In [45]:
annot_cat = annotations_df.merge(categories_df,
                                 left_on="category_id",
                                 right_on="id",
                                 suffixes=("_annot", "_cat"))

In [48]:
annot_cat["audio_dir_name"][0]

'03612_Animalia_Chordata_Aves_Passeriformes_Passerellidae_Zonotrichia_albicollis'

In [41]:
annot_cat.supercategory.value_counts()

supercategory
Aves        111029
Amphibia     13183
Insecta      10080
Mammalia      2566
Reptilia       154
Name: count, dtype: int64

In [42]:
class_counts = (
    categories_df
    .groupby("supercategory")["id"]
    .nunique()
    .reset_index(name="num_species")
)

class_counts

  supercategory  num_species
0      Amphibia          650
1          Aves         3846
2       Insecta          745
3      Mammalia          296
4      Reptilia           32

In [46]:
audio_df

,id,duration,file_name,license,rights_holder,date,latitude,longitude,location_uncertainty
0,156691,4.296,train/03612_Animalia_Chordata_Aves_Passeriform...,0,Katie Kucera,2019-04-15T11:23:00-05:00,42.151129,-87.788503,8.0
1,182163,2.333,train/04361_Animalia_Chordata_Aves_Passeriform...,1,Jean Suplick,2021-09-23T09:12:00-05:00,33.038882,-96.664071,277.0
2,19703,15.250,train/00911_Animalia_Chordata_Amphibia_Anura_H...,1,Chris Harrison,2015-04-25T20:58:00-05:00,29.313880,-98.991786,NaN
3,61500,18.795,train/02061_Animalia_Chordata_Aves_Cuculiforme...,1,tkp123,2021-03-14T16:16:00+08:00,22.335805,114.149489,1106.0
4,224298,13.700,train/05147_Animalia_Chordata_Aves_Strigiforme...,0,Giacomo Piazza,2021-04-24T22:11:32+02:00,44.482806,11.278064,65.0
...,...,...,...,...,...,...,...,...,...
137007,139505,1.889,train/03479_Animalia_Chordata_Aves_Passeriform...,1,Jeff Ward,2021-04-16T09:31:00-07:00,44.058730,-123.095116,17.0
137008,102836,7.392,train/02760_Animalia_Chordata_Aves_Passeriform...,0,John A Haskins,2020-04-29T14:10:14-07:00,48.051094,-123.054914,NaN
137009,135022,17.579,train/03448_Animalia_Chordata_Aves_Passeriform...,1,mattvw,2020-10-09T16:37:03-07:00,40.859607,-124.091515,5.0
137010,73921,5.250,train/02376_Animalia_Chordata_Aves_Passeriform...,1,Haley H,2020-04-26,47.025984,-122.893084,NaN
137011,31711,10.937,train/01182_Animalia_Chordata_Amphibia_Anura_M...,1,Mango parker,2021-08-14T09:10:08+09:30,-35.389865,138.463698,115.0